"""
Mosquitto admin helper.

Espone una piccola API REST autenticata per gestire utenti e ACL del broker
Mosquitto. È pensata per essere usata SOLO dal container Django (web) sulla
rete docker interna, mai esposta fuori.

Endpoints:
    POST   /users                   crea/sovrascrive un utente
    DELETE /users/{username}        rimuove un utente
    POST   /acl                     riscrive completamente il file ACL
    POST   /reload                  invia SIGHUP a Mosquitto per ricaricare config
    GET    /health                  liveness check (no auth)

Autenticazione: header `Authorization: Bearer <MOSQUITTO_ADMIN_TOKEN>`.

Environment variables:
    MOSQUITTO_ADMIN_TOKEN           token condiviso con Django (richiesto)
    MOSQUITTO_CONTAINER_NAME        nome container Mosquitto da SIGHUPpare
                                    (default: device_monitoring_app-mosquitto-1)
    MOSQUITTO_CONFIG_DIR            path al config dir (default: /mosquitto/config)
"""

import logging
import os
import re
import subprocess
from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Header, Depends
from pydantic import BaseModel, Field

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("mosquitto-admin")

CONFIG_DIR = Path(os.getenv("MOSQUITTO_CONFIG_DIR", "/mosquitto/config"))
PASSWD_FILE = CONFIG_DIR / "passwd"
ACL_FILE = CONFIG_DIR / "acl"
MOSQUITTO_CONTAINER = os.getenv(
    "MOSQUITTO_CONTAINER_NAME", "device_monitoring_app-mosquitto-1"
)
TOKEN = os.getenv("MOSQUITTO_ADMIN_TOKEN", "")

if not TOKEN:
    raise RuntimeError("MOSQUITTO_ADMIN_TOKEN env var non impostata")

USERNAME_RE = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")

app = FastAPI(title="Mosquitto Admin Helper", version="1.0.0")


# ---------- auth ----------

def require_token(authorization: Optional[str] = Header(None)) -> None:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(401, "Missing bearer token")
    if authorization[7:] != TOKEN:
        raise HTTPException(403, "Invalid token")


# ---------- models ----------

class UserCreate(BaseModel):
    username: str = Field(..., min_length=1, max_length=64)
    password: str = Field(..., min_length=8, max_length=256)


class AclEntry(BaseModel):
    username: str = Field(..., min_length=1, max_length=64)
    topics: List[str] = Field(..., description="Lista topic con prefisso 'r ', 'w ' o 'rw '")


class AclWrite(BaseModel):
    """Riscrittura totale del file ACL.

    Ogni `entries` ha username e topics, dove ogni topic è prefissato con la
    permission ('r ', 'w ', 'rw ').

    Esempio:
        {"username": "django-consumer", "topics": ["r plants/#"]}
        {"username": "gw-1", "topics": ["rw plants/1/#"]}
    """
    entries: List[AclEntry]


# ---------- helper functions ----------

def validate_username(u: str) -> None:
    if not USERNAME_RE.match(u):
        raise HTTPException(400, f"Username non valido: {u!r} (alfanum, _, -, max 64)")


def run_mosquitto_passwd(username: str, password: str) -> None:
    """Esegue mosquitto_passwd dentro un container effimero.

    Usiamo `docker exec` sul container Mosquitto già in esecuzione (ha il
    binario disponibile). In alternativa potremmo usare `docker run --rm`
    su un'immagine separata.
    """
    if not PASSWD_FILE.exists():
        # Crea il file con il primo utente. Mosquitto si aspetta un file
        # esistente, anche vuoto, monta sempre il volume.
        PASSWD_FILE.touch()

    cmd = [
        "docker",
        "exec",
        "-i",
        MOSQUITTO_CONTAINER,
        "mosquitto_passwd",
        "-b",
        "/mosquitto/config/passwd",
        username,
        password,
    ]
    logger.info("Adding/updating user %s in passwd", username)
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
    if proc.returncode != 0:
        logger.error("mosquitto_passwd failed: stdout=%r stderr=%r", proc.stdout, proc.stderr)
        raise HTTPException(500, f"mosquitto_passwd failed: {proc.stderr}")


def remove_user_from_passwd(username: str) -> bool:
    """Rimuove righe `username:...` dal file passwd. Ritorna True se modificato."""
    if not PASSWD_FILE.exists():
        return False
    lines = PASSWD_FILE.read_text().splitlines()
    new_lines = [ln for ln in lines if not ln.startswith(f"{username}:")]
    if len(new_lines) == len(lines):
        return False
    PASSWD_FILE.write_text("\n".join(new_lines) + ("\n" if new_lines else ""))
    return True


def write_acl(entries: List[AclEntry]) -> None:
    lines = [
        "# Generated by mosquitto-admin helper",
        "# DO NOT EDIT MANUALLY - rewrites overwrite all changes",
        "",
    ]
    for e in entries:
        validate_username(e.username)
        lines.append(f"user {e.username}")
        for t in e.topics:
            t = t.strip()
            if t.startswith("rw "):
                topic = t[3:].strip()
                lines.append(f"topic readwrite {topic}")
            elif t.startswith("r "):
                topic = t[2:].strip()
                lines.append(f"topic read {topic}")
            elif t.startswith("w "):
                topic = t[2:].strip()
                lines.append(f"topic write {topic}")
            else:
                # default: readwrite
                lines.append(f"topic readwrite {t}")
        lines.append("")
    ACL_FILE.write_text("\n".join(lines))
    logger.info("ACL rewritten with %d users", len(entries))


def reload_mosquitto() -> None:
    """Manda SIGHUP al container Mosquitto per ricaricare passwd/acl."""
    cmd = ["docker", "kill", "-s", "HUP", MOSQUITTO_CONTAINER]
    logger.info("Sending SIGHUP to %s", MOSQUITTO_CONTAINER)
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    if proc.returncode != 0:
        logger.error("docker kill failed: stderr=%r", proc.stderr)
        raise HTTPException(500, f"docker kill -s HUP failed: {proc.stderr}")


# ---------- endpoints ----------

@app.get("/health")
def health():
    return {
        "ok": True,
        "passwd_exists": PASSWD_FILE.exists(),
        "acl_exists": ACL_FILE.exists(),
        "mosquitto_container": MOSQUITTO_CONTAINER,
    }


@app.post("/users", dependencies=[Depends(require_token)])
def add_or_update_user(payload: UserCreate):
    validate_username(payload.username)
    run_mosquitto_passwd(payload.username, payload.password)
    return {"ok": True, "username": payload.username}


@app.delete("/users/{username}", dependencies=[Depends(require_token)])
def remove_user(username: str):
    validate_username(username)
    removed = remove_user_from_passwd(username)
    return {"ok": True, "username": username, "removed": removed}


@app.post("/acl", dependencies=[Depends(require_token)])
def rewrite_acl(payload: AclWrite):
    write_acl(payload.entries)
    return {"ok": True, "entries": len(payload.entries)}


@app.post("/reload", dependencies=[Depends(require_token)])
def reload():
    reload_mosquitto()
    return {"ok": True}
