# Generated by Django 5.1.1 on 2026-10-08 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable/Disable monitoring for this device')),
                ('slave_id', models.IntegerField(blank=True, default=-1, help_text='Slave ID of the device(nr between 1 to 247)', null=True)),
                ('port', models.IntegerField(default=0)),
                ('availability', models.FloatField(default=0, help_text='Availability of the device')),
                ('show_energy', models.BooleanField(default=False, help_text='Show real time energy production/consumption')),
                ('show_energy_daily', models.BooleanField(default=False, help_text='Show daily energy production/consumption')),
                ('show_energy_weekly', models.BooleanField(default=False, help_text='Show weekly energy production/consumption')),
                ('show_energy_monthly', models.BooleanField(default=False, help_text='Show monthly energy production/consumption')),
                ('daily_production', models.FloatField(default=0, help_text='Daily production of the device')),
                ('daily_consumption', models.FloatField(default=0, help_text='Daily consumption of the device')),
                ('protocol', models.CharField(choices=[('modbus', 'MODBUS'), ('dlms', 'DLMS')], default='modbus', help_text='Type of protocol for the readings', max_length=10)),
                ('preset', models.CharField(blank=True, default='', help_text='Preset di mappatura applicato alla creazione (vuoto = mappatura manuale)', max_length=150)),
                ('user', models.ManyToManyField(related_name='user_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputedVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_type', models.CharField(choices=[('memory', 'Memory Mapping'), ('computed', 'Computed Variable')], default='memory', help_text='Choose the type of variable to configure (Memory Mapping or Computed Variable)', max_length=10)),
                ('var_name', models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g., V, A, W)', max_length=20, null=True)),
                ('show_on_graph', models.BooleanField(default=False, help_text='Show this variable on the graph')),
                ('show_in_homepage', models.BooleanField(default=False, help_text='Show this variable in the homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('formula', models.TextField(help_text="Formula to calculate the value (e.g., 'voltage * current'). Variables must match existing MemoryMapping variable names")),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_variables', to='user_devices.device')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DlmsMappingVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_type', models.CharField(choices=[('memory', 'Memory Mapping'), ('computed', 'Computed Variable')], default='memory', help_text='Choose the type of variable to configure (Memory Mapping or Computed Variable)', max_length=10)),
                ('var_name', models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g., V, A, W)', max_length=20, null=True)),
                ('show_on_graph', models.BooleanField(default=False, help_text='Show this variable on the graph')),
                ('show_in_homepage', models.BooleanField(default=False, help_text='Show this variable in the homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('conversion_factor', models.CharField(blank=True, default='1', help_text='Factor to convert raw data to physical value', null=True)),
                ('obis_code', models.CharField(blank=True, default='', help_text='Address of the mapped value', null=True)),
                ('column_idx', models.IntegerField(default=1, help_text='Column of the profile generic to read')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dlms_variables', to='user_devices.device')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='not assigned', max_length=50)),
                ('ssh_username', models.CharField(default='ssh_user', max_length=50)),
                ('ssh_password', models.CharField(default='ssh_psw', max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('performance_factor', models.FloatField(default=0, help_text='Performance factor of the plant')),
                ('protocol_mode', models.CharField(choices=[('mqtt', 'MQTT (gateway pubblica via Telegraf)'), ('modbus_direct', 'Modbus TCP diretto (server fa polling via mbusd in VPN)'), ('dlms', 'DLMS (smart meter, polling diretto)')], default='mqtt', help_text='MQTT: il gateway pubblica via Telegraf, server consuma. Modbus TCP diretto: server fa polling Modbus TCP via mbusd in VPN (modalità legacy, utile per debug e per gateway non ancora migrati). DLMS: smart meter via DLMS/COSEM.', max_length=20)),
                ('user', models.ManyToManyField(related_name='user_gateway', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_data', to='user_devices.device')),
                ('user', models.ManyToManyField(related_name='user_energy_data', to=settings.AUTH_USER_MODEL)),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_energy_data', to='user_devices.gateway')),
            ],
            options={
                'verbose_name': 'Energy Data',
                'verbose_name_plural': 'Energy Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='user_devices.device')),
                ('user', models.ManyToManyField(related_name='user_device_data', to=settings.AUTH_USER_MODEL)),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_device_data', to='user_devices.gateway')),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='Gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user_devices.gateway'),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('pin_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('show_in_user_page', models.BooleanField(default=False)),
                ('Gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='user_devices.gateway')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='GatewayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_data', to='user_devices.gateway')),
                ('user', models.ManyToManyField(related_name='user_gateway_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gateway Data',
                'verbose_name_plural': 'Gateway Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GatewayMqttCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_plaintext', models.CharField(blank=True, default='', help_text='Password in chiaro mostrata UNA volta dopo la creazione. Verrà azzerata dopo il primo accesso/visualizzazione.', max_length=128)),
                ('password_revealed', models.BooleanField(default=False, help_text='True dopo che la password è stata vista almeno una volta.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_credentials', to='user_devices.gateway')),
            ],
            options={
                'verbose_name': 'Gateway MQTT credentials',
                'verbose_name_plural': 'Gateway MQTT credentials',
            },
        ),
        migrations.CreateModel(
            name='ModbusMappingVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_type', models.CharField(choices=[('memory', 'Memory Mapping'), ('computed', 'Computed Variable')], default='memory', help_text='Choose the type of variable to configure (Memory Mapping or Computed Variable)', max_length=10)),
                ('var_name', models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g., V, A, W)', max_length=20, null=True)),
                ('show_on_graph', models.BooleanField(default=False, help_text='Show this variable on the graph')),
                ('show_in_homepage', models.BooleanField(default=False, help_text='Show this variable in the homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('register_type', models.CharField(choices=[('input', 'Input Register'), ('holding', 'Holding Register')], default='input', help_text='Type of Modbus register (Input or Holding)', max_length=10)),
                ('address', models.CharField(blank=True, default='', help_text='Address of the mapped value', null=True)),
                ('conversion_factor', models.CharField(blank=True, default='1', help_text='Factor to convert raw data to physical value', null=True)),
                ('offset', models.FloatField(default=0, help_text='Valore sottratto al dato grezzo prima del conversion factor: (raw - offset) * factor')),
                ('bit_length', models.PositiveIntegerField(choices=[(16, '16 bit'), (32, '32 bit'), (64, '64 bit')], default=16, help_text='Bit length of the register (16, 32, 64)')),
                ('is_signed', models.BooleanField(default=False, help_text='Interpret value as signed (True) or unsigned (False)')),
                ('endianness', models.CharField(choices=[('big', 'Big Endian'), ('little', 'Little Endian')], default='big', help_text='Endianness of the register (Big Endian or Little Endian)', max_length=10)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modbus_variables', to='user_devices.device')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModbusReadBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(choices=[('input', 'Input Register'), ('holding', 'Holding Register')], default='input', help_text='Type of Modbus register to read (Input or Holding)', max_length=10)),
                ('start_address', models.CharField(default='0x0000', help_text='Starting Modbus address in hexadecimal (e.g., 0x0280)', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=1, help_text='Total number of consecutive words to read')),
                ('order', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_blocks', to='user_devices.device')),
            ],
            options={
                'verbose_name': 'Modbus read block',
                'verbose_name_plural': 'Modbus read blocks',
                'ordering': ['order'],
            },
        ),
    ]
