# Generated by hand — aggiunge GatewayMqttCredentials

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_devices", "0012_gateway_use_mqtt"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayMqttCredentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gateway",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="mqtt_credentials",
                        to="user_devices.gateway",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                (
                    "password_plaintext",
                    models.CharField(
                        max_length=128,
                        blank=True,
                        default="",
                        help_text=(
                            "Password in chiaro mostrata UNA volta dopo la creazione. "
                            "Verrà azzerata dopo il primo accesso/visualizzazione."
                        ),
                    ),
                ),
                (
                    "password_revealed",
                    models.BooleanField(
                        default=False,
                        help_text="True dopo che la password è stata vista almeno una volta.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gateway MQTT credentials",
                "verbose_name_plural": "Gateway MQTT credentials",
            },
        ),
    ]
