# Generated by hand — blocchi di lettura Modbus multipli + preset di mappatura
#
# Ogni device Modbus esistente diventa un device con un solo ModbusReadBlock
# (stessi start_address/word_count/register_type), e le sue variabili prendono
# il register_type del device: il comportamento resta identico a prima.

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Device = apps.get_model("user_devices", "Device")
    ModbusReadBlock = apps.get_model("user_devices", "ModbusReadBlock")
    ModbusMappingVariable = apps.get_model("user_devices", "ModbusMappingVariable")

    for device in Device.objects.all():
        register_type = device.register_type or "input"
        ModbusMappingVariable.objects.filter(device=device).update(register_type=register_type)
        if device.protocol != "modbus" or not device.start_address or not device.word_count:
            continue
        start = str(device.start_address)
        try:
            start = f"0x{int(start, 16):04X}"
        except ValueError:
            pass
        ModbusReadBlock.objects.create(
            device=device,
            register_type=register_type,
            start_address=start,
            word_count=device.word_count,
            order=0,
        )


def backwards(apps, schema_editor):
    Device = apps.get_model("user_devices", "Device")
    for device in Device.objects.all():
        block = device.read_blocks.order_by("order").first()
        if block:
            device.register_type = block.register_type
            device.start_address = block.start_address
            device.word_count = block.word_count
            device.save(update_fields=["register_type", "start_address", "word_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("user_devices", "0013_gatewaymqttcredentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModbusReadBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("register_type", models.CharField(choices=[("input", "Input Register"), ("holding", "Holding Register")], default="input", help_text="Type of Modbus register to read (Input or Holding)", max_length=10)),
                ("start_address", models.CharField(default="0x0000", help_text="Starting Modbus address in hexadecimal (e.g., 0x0280)", max_length=10)),
                ("word_count", models.PositiveIntegerField(default=1, help_text="Total number of consecutive words to read")),
                ("order", models.PositiveIntegerField(default=0)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_blocks", to="user_devices.device")),
            ],
            options={
                "verbose_name": "Modbus read block",
                "verbose_name_plural": "Modbus read blocks",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="modbusmappingvariable",
            name="register_type",
            field=models.CharField(choices=[("input", "Input Register"), ("holding", "Holding Register")], default="input", help_text="Type of Modbus register (Input or Holding)", max_length=10),
        ),
        migrations.AddField(
            model_name="modbusmappingvariable",
            name="offset",
            field=models.FloatField(default=0, help_text="Valore sottratto al dato grezzo prima del conversion factor: (raw - offset) * factor"),
        ),
        migrations.AddField(
            model_name="device",
            name="preset",
            field=models.CharField(blank=True, default="", help_text="Preset di mappatura applicato alla creazione (vuoto = mappatura manuale)", max_length=150),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(model_name="device", name="start_address"),
        migrations.RemoveField(model_name="device", name="word_count"),
        migrations.RemoveField(model_name="device", name="register_type"),
    ]
