"""
Genera telegraf.conf per un gateway, leggendo la configurazione dal DB.

Uso:
    python manage.py export_telegraf_config <gateway_pk> [--out telegraf.conf] [--interval 30s]

Per ogni Device modbus abilitato del gateway, produce una sezione
[[inputs.modbus]] con configuration_type = "request" che chiede un blocco
di `word_count` registri a partire da `start_address`.
Telegraf pubblicherà ciascun registro come field `reg_0xNNNN`.

L'output MQTT è unico (un solo [[outputs.mqtt_v2]]) e topic-routing con
`topic = "plants/{gateway_pk}/devices/{device_pk}/raw"` usando tag
interpolation.

Segreti (user/pass MQTT, path CA) restano fuori dal DB: vengono letti da env
all'avvio di Telegraf sul gateway, vedi gateway_setup/telegraf.env.example.
"""

import sys
from django.core.management.base import BaseCommand, CommandError

from user_devices.models import Gateway, Device


def _chunks(start, count, size):
    """Itera blocchi (addr, length) di al più `size` registri per restare
    sotto il limite Modbus di 125 registri/read (input/holding)."""
    off = 0
    while off < count:
        n = min(size, count - off)
        yield start + off, n
        off += n


def _render_request_block(device: Device, gateway: Gateway, interval: str) -> str:
    try:
        start_address = int(device.start_address, 16)
    except (ValueError, TypeError) as exc:
        raise CommandError(
            f"Device '{device.name}' (pk={device.pk}) ha start_address non valido: "
            f"{device.start_address!r}"
        ) from exc

    word_count = int(device.word_count or 0)
    if word_count <= 0:
        raise CommandError(
            f"Device '{device.name}' (pk={device.pk}) ha word_count <= 0"
        )

    register_type = "holding" if device.register_type == "holding" else "input"

    # Genera il blocco [[inputs.modbus.request.fields]] per ogni registro.
    # Telegraf richiede un field per address; chiamiamoli reg_0xNNNN.
    field_lines = []
    for addr in range(start_address, start_address + word_count):
        field_lines.append(
            f'    {{ address = {addr}, name = "reg_0x{addr:04x}", type = "UINT16" }},'
        )
    fields_toml = "\n".join(field_lines)

    # Blocchi di request: Telegraf li aggrega in burst Modbus efficienti.
    # Qui un singolo request copre tutto il range: Telegraf internamente
    # spezza in pacchetti <= 125 registri.
    return f"""
# -----------------------------------------------------------------------------
# Device: {device.name} (pk={device.pk}, slave_id={device.slave_id}, port={device.port})
# -----------------------------------------------------------------------------
[[inputs.modbus]]
  name = "modbus"
  slave_id = {int(device.slave_id)}
  timeout = "5s"
  busy_retries = 3
  busy_retries_wait = "200ms"
  controller = "tcp://127.0.0.1:{int(device.port)}"
  transmission_mode = "TCP"
  configuration_type = "request"
  interval = "{interval}"

  [[inputs.modbus.request]]
    slave_id = {int(device.slave_id)}
    byte_order = "ABCD"
    register = "{register_type}"
    fields = [
{fields_toml}
    ]
    tags = {{ gateway_id = "{gateway.pk}", device_id = "{device.pk}" }}
""".strip()


def _render_header(gateway: Gateway, interval: str) -> str:
    return f"""# Telegraf configuration for gateway pk={gateway.pk} name="{gateway.name}"
# Generated by Django management command: export_telegraf_config
# ATTENZIONE: non modificare a mano. Rigenera con:
#   python manage.py export_telegraf_config {gateway.pk} --out telegraf.conf

[agent]
  interval = "{interval}"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "{interval}"
  flush_jitter = "0s"
  precision = "1s"
  hostname = "gateway-{gateway.pk}"
  omit_hostname = false
  logfile = "/var/log/telegraf/telegraf.log"
  debug = false
  quiet = false

# -----------------------------------------------------------------------------
# OUTPUT MQTT
# Username/password/CA vanno in /etc/default/telegraf come env, vedi
# telegraf.env.example. I placeholder ${{...}} sono interpolati da Telegraf
# all'avvio.
# -----------------------------------------------------------------------------
[[outputs.mqtt]]
  servers = ["${{MQTT_SERVER}}"]
  protocol = "5"
  keep_alive = 30
  client_id = "gateway-{gateway.pk}"
  username = "${{MQTT_USERNAME}}"
  password = "${{MQTT_PASSWORD}}"
  topic = 'plants/{gateway.pk}/devices/{{{{ .Tag "device_id" }}}}/raw'
  qos = 1
  retain = true
  data_format = "json"
  json_timestamp_units = "1s"
  # TLS - se usi cert self-signed, tieni tls_ca; se Let's Encrypt con CA pubblica,
  # puoi rimuovere tls_ca ma lasciare insecure_skip_verify=false
  tls_ca = "${{MQTT_TLS_CA}}"
  insecure_skip_verify = false

# -----------------------------------------------------------------------------
# LWT gateway: Telegraf pubblica un heartbeat internal ogni ciclo.
# In questo setup non c'è un vero LWT nativo di outputs.mqtt con paho-go;
# il consumer lato server usa la freshness cache per decretare offline.
# -----------------------------------------------------------------------------

[[inputs.internal]]
  collect_memstats = false
  name_override = "telegraf_self"
  [inputs.internal.tags]
    gateway_id = "{gateway.pk}"
""".strip()


class Command(BaseCommand):
    help = "Esporta telegraf.conf per un gateway leggendo Device e ModbusMappingVariable dal DB"

    def add_arguments(self, parser):
        parser.add_argument("gateway_pk", type=int, help="Primary key del Gateway")
        parser.add_argument(
            "--out",
            type=str,
            default=None,
            help="File di output. Se omesso, scrive su stdout.",
        )
        parser.add_argument(
            "--interval",
            type=str,
            default="30s",
            help="Intervallo di polling Telegraf (default: 30s)",
        )

    def handle(self, *args, **options):
        gateway_pk = options["gateway_pk"]
        out_path = options["out"]
        interval = options["interval"]

        try:
            gateway = Gateway.objects.get(pk=gateway_pk)
        except Gateway.DoesNotExist as exc:
            raise CommandError(f"Gateway pk={gateway_pk} non trovato") from exc

        devices = Device.objects.filter(
            Gateway=gateway,
            is_enabled=True,
            protocol="modbus",
        ).order_by("port", "slave_id")

        if not devices.exists():
            raise CommandError(
                f"Nessun device modbus abilitato trovato per gateway pk={gateway_pk}"
            )

        sections = [_render_header(gateway, interval)]
        for device in devices:
            sections.append(_render_request_block(device, gateway, interval))

        config = "\n\n".join(sections) + "\n"

        if out_path:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(config)
            self.stdout.write(
                self.style.SUCCESS(
                    f"Scritto {out_path} ({len(devices)} device modbus, interval={interval})"
                )
            )
        else:
            sys.stdout.write(config)
